# 行列演算の基礎

$
  w = (X^TX)^{-1}X^Ty
$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [2]:
import numpy as np

In [ ]:
# ベクトルの定義

In [15]:
# 縦（1つの配列が行を表している）
x = np.array([[1], [2], [3]])
print(x)
print(x.T)
# 横
xt = np.array([[1, 2, 3]])
print(xt)

[[1]
 [2]
 [3]]
[[1 2 3]]
[[1 2 3]]


In [5]:
# 行列の定義
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [9]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [10]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よく使うお便利

In [16]:
row, col = X.shape

In [18]:
print(f'{row=} {col=}')

row=2 col=2


# 重回帰分析の実装

$
  X = 
  \left[\begin{array}{}
    1 & 2 & 3 \\
    1 & 2 & 5 \\
    1 & 3 & 4 \\
    1 & 5 & 9
  \end{array}\right]
  y = 
  \left[\begin{array}{}
  1 \\
  5 \\
  6 \\
  8
  \end{array}\right] の時\\
  w = (X^TX)^{-1}X^Ty
$

In [21]:
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])
y = np.array([[1], [5], [6], [8]])

In [23]:
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [24]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [25]:
Xty = np.dot(X.T, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [27]:
w = np.dot(XtX_inv, Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# Scikit-learnでの実装

In [30]:
# LinearRegressionは重回帰分析
from sklearn.linear_model import LinearRegression

## Module NotFound Errorになる場合
wsl上のubuntuで、
pip install scilit-learn

In [31]:
# モデルの宣言
model = LinearRegression()

In [32]:
# モデルの学習U（パラメータ調整のこと）
model.fit(X, y)

LinearRegression()

In [41]:
# 調整後のパラメータ（パラメータwのこと）
print(model.coef_)
print(model.intercept_)  # 切片

[[0.         0.71428571 0.57142857]]
[-0.14285714]


In [37]:
# 予測精度（決定係数） 1に近づけば近づくほど良い。
model.score(X, y)

0.6923076923076922

In [42]:
# 予測値の計算
x5 = np.array([[1, 2, 3]])  # 新しい入力値x5
model.predict(x5)

array([[3.]])