## Numpy

In [46]:
import numpy as np

## ベクトルの定義

In [48]:
x = np.array([1, 2, 3])

In [49]:
x

array([1, 2, 3])

In [50]:
y = np.array([2., 3.9, 6.1])

In [51]:
y

array([2. , 3.9, 6.1])

## データの中心化

In [54]:
# 平均の算出

2.0

In [56]:
xc = x - x.mean()

In [57]:
xc

array([-1.,  0.,  1.])

In [58]:
yc = y - y.mean()

In [59]:
yc

array([-2. , -0.1,  2.1])

## パラメータaの計算

In [63]:
# 要素ごとの掛け算
xx = xc * xc

In [70]:
xy = xc * yc

In [71]:
a = xy.sum() / xx.sum()

In [72]:
a

2.05